version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /el_hub_server/
    destination: /home/ec2-user/serverpod/upload/el_hub_server/
hooks:
  BeforeInstall:
    - location: el_hub_server/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: el_hub_server/aws/scripts/start_server
      timeout: 300
      runas: root
