name: el_hub_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  logger: ^1.3.0
  mailer: ^6.0.0
  serverpod: ^1.0.0
  serverpod_auth_server: ^1.0.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
